version: "2.7"
services:
  postgres:
    image: postgres:15.6-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: robodev-api
volumes:
  postgres-data: {}
