version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - local-myapp-dbdata:/var/lib/postgresql/data
    networks:
      - local-myapp-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  localstack:
    image: localstack/localstack:2.2.0
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost
      - SERVICES=s3
    volumes:
      - ./tools/localstack:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      bash -c "chmod 777 -R /tmp/localstack
      && /usr/local/bin/docker-entrypoint.sh"
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    networks:
      - local-myapp-network

volumes:
  local-myapp-dbdata:

networks:
  local-myapp-network:
