version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - test-myapp-dbdata:/var/lib/postgresql/data
    networks:
      - test-myapp-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  test-myapp-dbdata:

networks:
  test-myapp-network:
