project:
  name: robodev-api
  #description:

~common/logging:
  # basic, pino, sentry, highlight
  provider: basic

dot-config:
  bootstrap: false

# AWS ECS Deploy Cli
ecs-deploy-cli:
  bootstrap: true
  mode: enabled
  stages:
    - robodev-api-dev

~database/prisma:
  mode: enabled

~common/http/openapi:
  # disabled, static, runtime
  mode: runtime
  # served on /docs-json
  path: docs
