nodeLinker: "node-modules"


packageExtensions:
  "@adminjs/design-system@4.1.0":
    dependencies:
      react-dom: ^18.2.0
  "@babel/plugin-syntax-jsx@7.23.3":
    dependencies:
      "@babel/core": ^7.23.3
  "@hypnosphi/create-react-context@0.3.1":
    dependencies:
      prop-types: ^15.8.1
  "@tiptap/starter-kit@2.0.1":
    dependencies:
      "@tiptap/pm": ^2.1.12
  styled-components@5.3.9:
    dependencies:
      react-is: ^18.2.0
  ts-node@10.9.1:
    dependencies:
      "@types/node": ^16.18.0
